Rename message variable to avoid confusions
The message variable in the output methods are strings and should not be
confused with the global array with the same name.

diff --git a/symlink-creator b/symlink-creator
--- a/symlink-creator
+++ b/symlink-creator
@@ -13,11 +13,11 @@ getMessage() {
 }
 
 question() {
-    local message="$1"
+    local msg="$1"
     if [ "$X" ]; then
-        zenity --question --no-wrap --text "$message" || exit 1
+        zenity --question --no-wrap --text "$msg" || exit 1
     else
-        echo "$message"
+        echo "$msg"
         read answer
         case "$answer" in
             y | yes) ;;
@@ -27,38 +27,38 @@ question() {
 }
 
 info() {
-    local message="$1"
+    local msg="$1"
     if [ "$X" ]; then
-        zenity --info --no-wrap --text "$message"
+        zenity --info --no-wrap --text "$msg"
     else
-        echo "$message"
+        echo "$msg"
     fi
 }
 
 warning() {
-    local message="$1"
+    local msg="$1"
     if [ "$X" ]; then
-        zenity --warning --no-wrap --text "$message"
+        zenity --warning --no-wrap --text "$msg"
     else
-        echo "WARNING: $message" >&2
+        echo "WARNING: $msg" >&2
     fi
 }
 
 error() {
-    local message="$1"
+    local msg="$1"
     if [ "$X" ]; then
-        zenity --error --no-wrap --text "$message"
+        zenity --error --no-wrap --text "$msg"
     else
-        echo "*** ERROR: $message" >&2
+        echo "*** ERROR: $msg" >&2
     fi
 }
 
 progress() {
-    local message="$1"
+    local msg="$1"
     if [ "$X" ]; then
-        zenity --progress --pulsate --auto-close --auto-kill --text "$message"
+        zenity --progress --pulsate --auto-close --auto-kill --text "$msg"
     else
-        echo -n "$message"
+        echo -n "$msg"
         while read _; do :; done
         echo
         echo "Done."
